INSERT INTO table1 (a, b) VALUES(1, 'a\r');
INSERT INTO table1 (a, b) VALUES(2, 'b\r');
INSERT INTO table1 (a, b) VALUES(3, 'c\r');
INSERT INTO table1 (a, b) VALUES(4, 'd\r');
INSERT INTO table1 (a, b) VALUES(5, 'e\r');
INSERT INTO table1 (a, b) VALUES(6, 'a\r');
INSERT INTO table1 (a, b) VALUES(7, 'b\r');
INSERT INTO table1 (a, b) VALUES(8, 'c\r');
INSERT INTO table1 (a, b) VALUES(9, 'd\r');
INSERT INTO table1 (a, b) VALUES(10, 'e\r');
INSERT INTO table1 (a, b) VALUES(11, 'a\r');
INSERT INTO table1 (a, b) VALUES(12, 'b\r');
INSERT INTO table1 (a, b) VALUES(13, 'c\r');
INSERT INTO table1 (a, b) VALUES(1, 'a\r');
INSERT INTO table1 (a, b) VALUES(2, 'b\r');
INSERT INTO table1 (a, b) VALUES(3, 'c\r');
INSERT INTO table1 (a, b) VALUES(4, 'd\r');
INSERT INTO table1 (a, b) VALUES(5, 'e\r');
INSERT INTO table1 (a, b) VALUES(6, 'a\r');
INSERT INTO table1 (a, b) VALUES(7, 'b\r');
INSERT INTO table1 (a, b) VALUES(8, 'c\r');
INSERT INTO table1 (a, b) VALUES(9, 'd\r');
INSERT INTO table1 (a, b) VALUES(10, 'e\r');
INSERT INTO table1 (a, b) VALUES(11, 'a\r');
INSERT INTO table1 (a, b) VALUES(12, 'b\r');
INSERT INTO table1 (a, b) VALUES(13, 'c\r');
INSERT INTO table2 (a, b, c) VALUES(1, 'a', 'aa\r');
INSERT INTO table2 (a, b, c) VALUES(2, 'b', 'bb\r');
INSERT INTO table2 (a, b, c) VALUES(3, 'c', 'cc\r');
INSERT INTO table2 (a, b, c) VALUES(4, 'a', 'aa\r');
INSERT INTO table2 (a, b, c) VALUES(5, 'b', 'bb\r');
INSERT INTO table2 (a, b, c) VALUES(6, 'c', 'cc\r');
INSERT INTO table2 (a, b, c) VALUES(7, 'a', 'aa\r');
INSERT INTO table2 (a, b, c) VALUES(8, 'b', 'bb\r');
INSERT INTO table2 (a, b, c) VALUES(9, 'c', 'cc\r');
INSERT INTO table2 (a, b, c) VALUES(10, 'a', 'aa\r');
INSERT INTO table2 (a, b, c) VALUES(11, 'b', 'bb\r');
INSERT INTO table2 (a, b, c) VALUES(12, 'c', 'cc\r');
INSERT INTO table2 (a, b, c) VALUES(13, 'a', 'aa\r');
INSERT INTO table2 (a, b, c) VALUES(14, 'b', 'bb\r');
INSERT INTO table2 (a, b, c) VALUES(15, 'c', 'cc\r');
INSERT INTO table2 (a, b, c) VALUES(16, 'a', 'aa\r');
INSERT INTO table2 (a, b, c) VALUES(17, 'b', 'bb\r');
INSERT INTO table1 (a, b) VALUES(1, 'a\r');
INSERT INTO table1 (a, b) VALUES(2, 'b\r');
INSERT INTO table1 (a, b) VALUES(3, 'c\r');
INSERT INTO table1 (a, b) VALUES(4, 'd\r');
INSERT INTO table1 (a, b) VALUES(5, 'e\r');
INSERT INTO table1 (a, b) VALUES(6, 'a\r');
INSERT INTO table1 (a, b) VALUES(7, 'b\r');
INSERT INTO table1 (a, b) VALUES(8, 'c\r');
INSERT INTO table1 (a, b) VALUES(9, 'd\r');
INSERT INTO table1 (a, b) VALUES(10, 'e\r');
INSERT INTO table1 (a, b) VALUES(11, 'a\r');
INSERT INTO table1 (a, b) VALUES(12, 'b\r');
INSERT INTO table1 (a, b) VALUES(13, 'c\r');
INSERT INTO table2 (a, b, c) VALUES(1, 'a', 'aa\r');
INSERT INTO table2 (a, b, c) VALUES(2, 'b', 'bb\r');
INSERT INTO table2 (a, b, c) VALUES(3, 'c', 'cc\r');
INSERT INTO table2 (a, b, c) VALUES(4, 'a', 'aa\r');
INSERT INTO table2 (a, b, c) VALUES(5, 'b', 'bb\r');
INSERT INTO table2 (a, b, c) VALUES(6, 'c', 'cc\r');
INSERT INTO table2 (a, b, c) VALUES(7, 'a', 'aa\r');
INSERT INTO table2 (a, b, c) VALUES(8, 'b', 'bb\r');
INSERT INTO table2 (a, b, c) VALUES(9, 'c', 'cc\r');
INSERT INTO table2 (a, b, c) VALUES(10, 'a', 'aa\r');
INSERT INTO table2 (a, b, c) VALUES(11, 'b', 'bb\r');
INSERT INTO table2 (a, b, c) VALUES(12, 'c', 'cc\r');
INSERT INTO table2 (a, b, c) VALUES(13, 'a', 'aa\r');
INSERT INTO table2 (a, b, c) VALUES(14, 'b', 'bb\r');
INSERT INTO table2 (a, b, c) VALUES(15, 'c', 'cc\r');
INSERT INTO table2 (a, b, c) VALUES(16, 'a', 'aa\r');
INSERT INTO table2 (a, b, c) VALUES(17, 'b', 'bb\r');
INSERT INTO table1 (a, b) VALUES(1, 'a');
INSERT INTO table1 (a, b) VALUES(2, 'b');
INSERT INTO table1 (a, b) VALUES(3, 'c');
INSERT INTO table1 (a, b) VALUES(4, 'd');
INSERT INTO table1 (a, b) VALUES(5, 'e');
INSERT INTO table1 (a, b) VALUES(6, 'a');
INSERT INTO table1 (a, b) VALUES(7, 'b');
INSERT INTO table1 (a, b) VALUES(8, 'c');
INSERT INTO table1 (a, b) VALUES(9, 'd');
INSERT INTO table1 (a, b) VALUES(10, 'e');
INSERT INTO table1 (a, b) VALUES(11, 'a');
INSERT INTO table1 (a, b) VALUES(12, 'b');
INSERT INTO table1 (a, b) VALUES(13, 'c');
INSERT INTO table2 (a, b, c) VALUES(1, 'a', 'aa');
INSERT INTO table2 (a, b, c) VALUES(2, 'b', 'bb');
INSERT INTO table2 (a, b, c) VALUES(3, 'c', 'cc');
INSERT INTO table2 (a, b, c) VALUES(4, 'a', 'aa');
INSERT INTO table2 (a, b, c) VALUES(5, 'b', 'bb');
INSERT INTO table2 (a, b, c) VALUES(6, 'c', 'cc');
INSERT INTO table2 (a, b, c) VALUES(7, 'a', 'aa');
INSERT INTO table2 (a, b, c) VALUES(8, 'b', 'bb');
INSERT INTO table2 (a, b, c) VALUES(9, 'c', 'cc');
INSERT INTO table2 (a, b, c) VALUES(10, 'a', 'aa');
INSERT INTO table2 (a, b, c) VALUES(11, 'b', 'bb');
INSERT INTO table2 (a, b, c) VALUES(12, 'c', 'cc');
INSERT INTO table2 (a, b, c) VALUES(13, 'a', 'aa');
INSERT INTO table2 (a, b, c) VALUES(14, 'b', 'bb');
INSERT INTO table2 (a, b, c) VALUES(15, 'c', 'cc');
INSERT INTO table2 (a, b, c) VALUES(16, 'a', 'aa');
INSERT INTO table2 (a, b, c) VALUES(17, 'b', 'bb');
